// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqvfrxsmtmprkugbqovs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdmZyeHNtdG1wcmt1Z2Jxb3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTIxMDEsImV4cCI6MjA2MTM2ODEwMX0.vdfmCRB4h4tGXdnfG19qrMfywMiQa1s5nWC3GtJVh6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);